"""empty message

Revision ID: 0c26dcf7baa0
Revises: 5a2e6bd3f62d
Create Date: 2023-07-02 18:04:58.897780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c26dcf7baa0'
down_revision = '5a2e6bd3f62d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
