"""empty message

Revision ID: 12ed8e1c5d5c
Revises: 5ddad817d77b
Create Date: 2023-07-02 16:49:11.834535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ed8e1c5d5c'
down_revision = '5ddad817d77b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
