"""empty message

Revision ID: 1f88d5c88ba3
Revises: 0c26dcf7baa0
Create Date: 2023-07-02 18:08:48.310323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f88d5c88ba3'
down_revision = '0c26dcf7baa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
