"""empty message

Revision ID: 73681973902f
Revises: 6f707dc7cf8f
Create Date: 2023-07-02 18:15:51.838131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73681973902f'
down_revision = '6f707dc7cf8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_post_dislikes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_post_likes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_post_likes')
    op.drop_table('user_post_dislikes')
    # ### end Alembic commands ###
