"""empty message

Revision ID: 7c09831046e1
Revises: 24b30bb5b076
Create Date: 2023-07-02 17:07:02.891800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c09831046e1'
down_revision = '24b30bb5b076'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
