"""empty message

Revision ID: 7df2afedc01f
Revises: 73681973902f
Create Date: 2023-07-02 21:45:32.371828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df2afedc01f'
down_revision = '73681973902f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_post')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_post',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='user_post_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_post_user_id_fkey')
    )
    # ### end Alembic commands ###
